'use strict';
// Destination cost data: accom = THB per room per night;
// food / transport / act = THB per person per day.
// flight = rough round-trip from Bangkok per person (0 = no airport / overland).
const DESTS = {
  bangkok:      { en: 'Bangkok', th: 'กรุงเทพฯ', emoji: '🏙️', flight: 0, slug12go: '',
    costs: { budget: [450, 250, 120, 150], mid: [1300, 550, 250, 400], comfort: [3500, 1400, 600, 900] } },
  chiangmai:    { en: 'Chiang Mai', th: 'เชียงใหม่', emoji: '⛰️', flight: 1900, slug12go: 'chiang-mai',
    costs: { budget: [350, 200, 100, 150], mid: [1000, 450, 200, 400], comfort: [2800, 1100, 500, 800] } },
  chiangrai:    { en: 'Chiang Rai', th: 'เชียงราย', emoji: '🛕', flight: 2000, slug12go: 'chiang-rai',
    costs: { budget: [300, 200, 100, 150], mid: [900, 400, 200, 350], comfort: [2500, 1000, 450, 700] } },
  phuket:       { en: 'Phuket', th: 'ภูเก็ต', emoji: '🏝️', flight: 2300, slug12go: 'phuket',
    costs: { budget: [500, 300, 180, 250], mid: [1600, 650, 350, 600], comfort: [4500, 1600, 700, 1200] } },
  krabi:        { en: 'Krabi', th: 'กระบี่', emoji: '🚤', flight: 2200, slug12go: 'krabi',
    costs: { budget: [450, 280, 150, 250], mid: [1400, 600, 300, 600], comfort: [4000, 1400, 600, 1100] } },
  kohsamui:     { en: 'Koh Samui', th: 'เกาะสมุย', emoji: '🥥', flight: 4200, slug12go: 'koh-samui',
    costs: { budget: [600, 320, 180, 250], mid: [1800, 700, 350, 600], comfort: [5000, 1700, 700, 1200] } },
  kohtao:       { en: 'Koh Tao', th: 'เกาะเต่า', emoji: '🤿', flight: 0, slug12go: 'koh-tao',
    costs: { budget: [500, 300, 150, 300], mid: [1500, 650, 300, 700], comfort: [3800, 1400, 600, 1300] } },
  pattaya:      { en: 'Pattaya', th: 'พัทยา', emoji: '🎡', flight: 0, slug12go: 'pattaya',
    costs: { budget: [450, 280, 150, 200], mid: [1300, 600, 300, 500], comfort: [3500, 1400, 600, 900] } },
  huahin:       { en: 'Hua Hin', th: 'หัวหิน', emoji: '🏖️', flight: 0, slug12go: 'hua-hin',
    costs: { budget: [450, 270, 130, 180], mid: [1300, 550, 250, 450], comfort: [3500, 1300, 550, 800] } },
  kanchanaburi: { en: 'Kanchanaburi', th: 'กาญจนบุรี', emoji: '🌉', flight: 0, slug12go: 'kanchanaburi',
    costs: { budget: [350, 220, 120, 180], mid: [900, 450, 250, 400], comfort: [2500, 1000, 500, 700] } },
  pai:          { en: 'Pai', th: 'ปาย', emoji: '🌄', flight: 0, slug12go: 'pai',
    costs: { budget: [300, 220, 100, 180], mid: [900, 450, 220, 400], comfort: [2200, 1000, 450, 700] } },
  kohchang:     { en: 'Koh Chang', th: 'เกาะช้าง', emoji: '🐘', flight: 0, slug12go: 'koh-chang',
    costs: { budget: [450, 280, 150, 220], mid: [1300, 600, 300, 500], comfort: [3500, 1300, 600, 900] } },
};

const CATS = [
  { id: 'accom', icon: 'bed' },
  { id: 'food', icon: 'bowl' },
  { id: 'transport', icon: 'bus' },
  { id: 'act', icon: 'ticket' },
  { id: 'flights', icon: 'plane' },
  { id: 'shopping', icon: 'bag' },
  { id: 'misc', icon: 'coins' },
];

const I18N = {
  en: {
    tagline: 'Plan your Thai trip budget in 30 seconds',
    newTrip: 'New Trip', myTrips: 'My trips', noTrips: 'No trips yet — plan your first one!',
    where: 'Where to?', nights: 'Nights', people: 'Travelers', style: 'Travel style',
    sBudget: 'Backpacker', sMid: 'Comfortable', sComfort: 'Premium',
    startDate: 'Start date (optional)', inclFlights: 'Include flights from Bangkok',
    create: 'Create trip & estimate budget',
    budget: 'Budget', expenses: 'Expenses', book: 'Book',
    total: 'Total budget', spent: 'Spent', remaining: 'Remaining', perPerson: 'per person',
    accom: 'Accommodation', food: 'Food & drinks', transport: 'Local transport',
    act: 'Activities', flights: 'Flights', shopping: 'Shopping', misc: 'Buffer / misc',
    addExpense: 'Add', amount: 'Amount (฿)', note: 'Note (optional)', noExpenses: 'No expenses yet — add your first one above.',
    reestimate: '↻ Re-estimate from averages', tapToEdit: 'Tap a number to edit it',
    bookTitle: 'Book your trip', bookHotelA: 'Hotels on Agoda', bookHotelB: 'Hotels on Booking.com',
    bookFlights: 'Flights on Trip.com', bookGround: 'Bus · Train · Ferry (12Go)', bookAct: 'Tours & tickets on Klook',
    bookHotelDesc: 'Best coverage in Thailand, pay at hotel options',
    bookFlightsDesc: 'Compare domestic and international fares',
    bookGroundDesc: 'Every route from Bangkok, book seats online',
    bookActDesc: 'Skip-the-line tickets, day trips, cooking classes',
    disclosure: 'Some links are affiliate links — booking through them may earn us a commission at no extra cost to you.',
    share: 'Share', deleteTrip: 'Delete trip', confirm: 'Tap again to confirm',
    over: 'over budget', daysLeft: 'nights', open: 'Open',
    sharedWith: 'planned with BudgetTrip',
    planBtn: 'I have a budget — plan for me',
    planTitle: 'How much do you have?',
    yourBudget: 'Your budget (฿)',
    planResults: 'With this budget you can go…',
    noFit: 'Budget too small for these settings — add more or switch style.',
    pickPlan: 'Pick this plan',
    left: 'left over',
    deal: 'Best deal',
    bestPicks: 'Best picks for your plan',
    bestBadge: 'TOP PICK',
    bookFood: 'Restaurant deals (Eatigo)',
    bookFoodDesc: 'Up to 50% off when you book a table ahead',
    bookFood2: 'Restaurant packages (Hungry Hub)',
    bookFood2Desc: 'Set menus & all-you-can-eat at fixed net prices',
    sortedNote: 'Sorted by where your money goes in this plan',
    recHotels: 'Recommended hotels', topActs: 'Top things to do', mustEat: 'Where locals eat',
    perNight: '/night', approxFrom: 'approx from', fitsPlan: 'fits your plan', freeEntry: 'free',
    mapBtn: 'Map', bookBtn: 'Book', morePartners: 'Search everything yourself',
    searchWorld: 'Search any city worldwide…', searching: 'Searching…',
    customNote: 'Smart estimate from country averages', anywhere: 'Or pick a Thai favorite',
  },
  th: {
    tagline: 'วางแผนงบเที่ยวไทยใน 30 วินาที',
    newTrip: 'ทริปใหม่', myTrips: 'ทริปของฉัน', noTrips: 'ยังไม่มีทริป — เริ่มวางแผนกันเลย!',
    where: 'ไปเที่ยวที่ไหน?', nights: 'จำนวนคืน', people: 'ผู้เดินทาง', style: 'สไตล์การเที่ยว',
    sBudget: 'ประหยัด', sMid: 'มาตรฐาน', sComfort: 'พรีเมียม',
    startDate: 'วันออกเดินทาง (ไม่บังคับ)', inclFlights: 'รวมตั๋วเครื่องบินจากกรุงเทพฯ',
    create: 'สร้างทริปและคำนวณงบ',
    budget: 'งบประมาณ', expenses: 'ค่าใช้จ่าย', book: 'จองเลย',
    total: 'งบทั้งหมด', spent: 'ใช้ไปแล้ว', remaining: 'คงเหลือ', perPerson: 'ต่อคน',
    accom: 'ที่พัก', food: 'อาหารและเครื่องดื่ม', transport: 'เดินทางในพื้นที่',
    act: 'กิจกรรม', flights: 'ตั๋วเครื่องบิน', shopping: 'ช้อปปิ้ง', misc: 'เผื่อฉุกเฉิน',
    addExpense: 'เพิ่ม', amount: 'จำนวนเงิน (฿)', note: 'บันทึก (ไม่บังคับ)', noExpenses: 'ยังไม่มีรายการ — เพิ่มรายการแรกด้านบนเลย',
    reestimate: '↻ คำนวณใหม่จากค่าเฉลี่ย', tapToEdit: 'แตะตัวเลขเพื่อแก้ไข',
    bookTitle: 'จองทริปของคุณ', bookHotelA: 'จองที่พักผ่าน Agoda', bookHotelB: 'ที่พักบน Booking.com',
    bookFlights: 'ตั๋วเครื่องบิน Trip.com', bookGround: 'รถทัวร์ · รถไฟ · เรือ (12Go)', bookAct: 'ทัวร์และตั๋วบน Klook',
    bookHotelDesc: 'ที่พักเยอะสุดในไทย มีแบบจ่ายที่โรงแรม',
    bookFlightsDesc: 'เทียบราคาตั๋วในประเทศและต่างประเทศ',
    bookGroundDesc: 'ทุกเส้นทางจากกรุงเทพฯ จองที่นั่งออนไลน์',
    bookActDesc: 'ตั๋วเข้าชม ทริปรายวัน คลาสทำอาหาร',
    disclosure: 'บางลิงก์เป็นลิงก์พันธมิตร — การจองผ่านลิงก์อาจทำให้เราได้รับค่าคอมมิชชั่น โดยคุณไม่เสียค่าใช้จ่ายเพิ่ม',
    share: 'แชร์', deleteTrip: 'ลบทริป', confirm: 'แตะอีกครั้งเพื่อยืนยัน',
    over: 'เกินงบ', daysLeft: 'คืน', open: 'เปิด',
    sharedWith: 'วางแผนด้วย BudgetTrip',
    planBtn: 'มีตังเท่านี้ ให้แอพวางแผน',
    planTitle: 'มีงบเท่าไหร่?',
    yourBudget: 'งบของคุณ (฿)',
    planResults: 'งบนี้ไปได้เลย…',
    noFit: 'งบยังไม่พอสำหรับเงื่อนไขนี้ — ลองเพิ่มงบหรือเปลี่ยนสไตล์ดูนะ',
    pickPlan: 'เลือกแผนนี้',
    left: 'เหลือ',
    deal: 'ดีลเด็ด',
    bestPicks: 'ดีลที่ดีที่สุดสำหรับแผนนี้',
    bestBadge: 'แนะนำ',
    bookFood: 'จองร้านอาหารลดสูงสุด 50% (Eatigo)',
    bookFoodDesc: 'จองโต๊ะล่วงหน้า รับส่วนลดทันที',
    bookFood2: 'แพ็กเกจร้านอาหาร (Hungry Hub)',
    bookFood2Desc: 'เซ็ตเมนู / บุฟเฟ่ต์ ราคาเหมาจ่ายชัดเจน',
    sortedNote: 'เรียงตามหมวดที่ใช้เงินเยอะสุดในแผนของคุณ',
    recHotels: 'โรงแรมแนะนำ', topActs: 'กิจกรรมยอดฮิต', mustEat: 'ร้านเด็ดต้องลอง',
    perNight: '/คืน', approxFrom: 'เริ่ม ~', fitsPlan: 'เหมาะกับแผนคุณ', freeEntry: 'ฟรี',
    mapBtn: 'แผนที่', bookBtn: 'จอง', morePartners: 'ค้นหาเองทั้งหมด',
    searchWorld: 'ค้นหาเมืองทั่วโลก เช่น Tokyo, Paris…', searching: 'กำลังค้นหา…',
    customNote: 'ประเมินอัจฉริยะจากค่าเฉลี่ยของประเทศ', anywhere: 'หรือเลือกที่เที่ยวยอดฮิตในไทย',
  },
};
